goc_platform_homepage:
    path:     /
    defaults: { _controller: GOCPlatformBundle:Default:index }
goc_platform_private:
    path:     /privpark
    defaults: { _controller: GOCPlatformBundle:Default:private }
goc_platform_application:
    path:    /apk
    defaults: { _controller: GOCPlatformBundle:Default:apk }
