services:
#    goc_platform.example:
#        class: GOC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    goc_platform.data:
        class: GOC\PlatformBundle\Datas